export enum ACTIONS_TYPE {
  IS_FETCHING = 'SignUp/IS_FETCHING',
  IS_SIGNUP_SUCCESSFUL = 'SignUp/IS_SIGNUP_SUCCESSFUL',
  SET_AUTH_SIGN_IN_DATA = 'SignIn/SET_AUTH_SIGN_IN_DATA',
  SET_ERROR_MESSAGE = 'SignIn/SET_ERROR_MESSAGE',
  SET_APP_STATUS = 'App/SET_STATUS',
  SET_APP_ERROR = 'App/SET_ERROR',
  APP_IS_INITIALIZED = 'App/IS_INITIALIZED',
}
