export enum ACTIONS_TYPE {
  REGISTRATION_IS_FETCHING = 'SignUp/REGISTRATION_IS_FETCHING',
  REGISTRATION_IS_SIGNUP_SUCCESSFUL = 'SignUp/REGISTRATION_IS_SIGNUP_SUCCESSFUL',
  SET_AUTH_SIGN_IN_DATA = 'SignIn/SET_AUTH_SIGN_IN_DATA',
  SET_ERROR_MESSAGE = 'SignIn/SET_ERROR_MESSAGE',
}
