export enum ACTIONS_TYPE {
  IS_FETCHING = 'SignUp/IS_FETCHING',
  IS_SIGN_UP_SUCCESSFUL = 'SignUp/IS_SIGN_UP_SUCCESSFUL',
  SET_AUTH_SIGN_IN_DATA = 'SignIn/SET_AUTH_SIGN_IN_DATA',
  SET_ERROR_MESSAGE = 'SignIn/SET_ERROR_MESSAGE',
  SET_APP_STATUS = 'App/SET_APP_STATUS',
  SET_APP_ERROR = 'App/SET_APP_ERROR',
  APP_IS_INITIALIZED = 'App/APP_IS_INITIALIZED',
  SERVER_ERROR = 'Errors/SERVER_ERROR',
  NETWORK_ERROR = 'Errors/NETWORK_ERROR',
}
